""" Describes values for enumerate fields """

__author__ = 'Andrey Kupriy'

TRANSACTION_STATUS_ENUM = ('NOT_FINAL', 'FINAL_FATAL', 'FINAL_SUCCESS')
CURRENCY_ENUM = ('USD', 'RUB', 'UAH', 'EUR')
PAYMENT_SYSTEMS_ID_ENUM = ('PAY_PAL', 'BIT_COIN', 'VISA_MASTER')
USER_NOTIFY_ENUM = ('EMAIL', 'PHONE', 'NONE')
SIGN_ALGORITHM_ENUM = ('MD5', 'SHA1',)
STORE_CATEGORY_ENUM = ('Dress', 'Children', 'Computers',)
PAYMENT_STATUS_ENUM = ('ACCEPTED', 'SUCCESS', '3D_SECURE', 'REJECTED')
