"""empty message

Revision ID: 0ceebaaef926
Revises: c7d6fd3f5420
Create Date: 2016-03-11 19:42:25.580896

"""

# revision identifiers, used by Alembic.
revision = '0ceebaaef926'
down_revision = 'c7d6fd3f5420'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_store_id_key', 'order', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('order_store_id_key', 'order', ['store_id'])
    ### end Alembic commands ###
