"""empty message

Revision ID: 8001590a8240
Revises: None
Create Date: 2016-03-14 13:55:26.996530

"""

# revision identifiers, used by Alembic.
revision = '8001590a8240'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'amount_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'amount_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    ### end Alembic commands ###
