"""empty message

Revision ID: c7d6fd3f5420
Revises: None
Create Date: 2016-03-11 17:08:29.946994

"""

# revision identifiers, used by Alembic.
revision = 'c7d6fd3f5420'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('item_id', sa.String(length=127), nullable=True))
    op.add_column('order', sa.Column('store_id', sa.String(length=127), nullable=False))
    op.drop_constraint('order_store_identifier_key', 'order', type_='unique')
    op.create_unique_constraint(None, 'order', ['store_id'])
    op.drop_column('order', 'item_identifier')
    op.drop_column('order', 'store_identifier')
    op.add_column('transaction', sa.Column('item_id', sa.String(length=127), nullable=True))
    op.add_column('transaction', sa.Column('store_id', sa.String(length=127), nullable=False))
    op.drop_column('transaction', 'item_identifier')
    op.drop_column('transaction', 'store_identifier')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('store_identifier', sa.VARCHAR(length=127), autoincrement=False, nullable=False))
    op.add_column('transaction', sa.Column('item_identifier', sa.VARCHAR(length=127), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'store_id')
    op.drop_column('transaction', 'item_id')
    op.add_column('order', sa.Column('store_identifier', sa.VARCHAR(length=127), autoincrement=False, nullable=False))
    op.add_column('order', sa.Column('item_identifier', sa.VARCHAR(length=127), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='unique')
    op.create_unique_constraint('order_store_identifier_key', 'order', ['store_identifier'])
    op.drop_column('order', 'store_id')
    op.drop_column('order', 'item_id')
    ### end Alembic commands ###
