"""empty message

Revision ID: c9b3859cc5d5
Revises: eb41f411b2ae
Create Date: 2016-03-04 18:25:31.277495

"""

# revision identifiers, used by Alembic.
revision = 'c9b3859cc5d5'
down_revision = 'eb41f411b2ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('test', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    ### end Alembic commands ###
