"""empty message

Revision ID: eb41f411b2ae
Revises: None
Create Date: 2016-03-04 18:24:56.135741

"""

# revision identifiers, used by Alembic.
revision = 'eb41f411b2ae'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('test', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'test')
    ### end Alembic commands ###
